import { useState, useEffect } from "react";

import Highlighter from "react-highlight-words";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState([]);
  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    if (query !== "") {
      setLoading(true);
      let url = "/api/forwardme?query=" + query;
      let response = fetch(url);
      response.then(async (res) => {
        res = await res.text();
        // console.log({ res });
        // res.split("####");
        setResults(res.split("####"));
        setLoading(false);
      });
    }
  }, [query]);

  function search() {
    setQuery(document.getElementById("searchFor").value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Clinical trial theMedNet demo for interview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Search a database of 15k clinical trials using medBERT</h1>
        <input type="text" id="searchFor" className="" />
        <input type="submit" value="Search" onClick={search} />
        <div className="clear">
          {isLoading
            ? "Loading..."
            : results.map((result) => (
                <>
                  <div className="card">
                    <Highlighter
                      highlightClassName="YourHighlightClass"
                      searchWords={query.split(" ")}
                      autoEscape={true}
                      textToHighlight={result.substring(0, 250)}
                    />
                    {/* <p>{result.substring(0, 250)}</p> */}
                  </div>
                </>
              ))}
        </div>
      </main>
    </div>
  );
}
